### PR TITLE
Use file streaming to support binary files and improve speed, fixes #14 

### LINKED ISSUE #14: zip-files are 0-size
Follow up on https://twitter.com/nkbtnk/status/667857528273813504

Broken: https://npmcdn.com/react-swap@1.3.1/build.zip

Works: https://npmcdn.com/react-swap@1.3.1/build/react-swap.js

Note: works in Chrome, broken in Vivaldi and Bower.

I am pretty sure it is because Content-Length header is missing. curl/wget/chrome are ok with this, bower/vivaldi are not

Will have a look soon and PR

### PR DESCRIPTION
**Pull request by nkbt**
Fixes problem with non-text files. So now it is possible to make full-featured Bower installs (with zip, see #6):

Plus:
1. In case of larger files requested, they will not be hold in memory
2. Streaming is fast :)

### CODE REVIEW

File: modules/ResponseUtils.js [hunk 1]
```diff
@@ -22,18 +22,18 @@ export function sendServerError(res, error) {
 }
 
 export function sendFile(res, file, maxAge=0) {
-  readFile(file, 'utf8', function (error, data) {
```
Comment (nkbt) [inline modules/ResponseUtils.js]: Just in case - when zip file was read as "text" in utf8 encoding it became invalid zip with almost doubled size:

```
23:03 $ curl -vk http://localhost:5000/react-swap@1.3.1/build.zip > b.zip
*   Trying 127.0.0.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /react-swap@1.3.1/build.zip HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.45.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Content-Type: application/zip; charset=utf-8
< Cache-Control: public, max-age=31536000
< Date: Thu, 17 Dec 2015 12:05:18 GMT
< Connection: keep-alive
< Content-Length: 7785
<
{ [7785 bytes data]
100  7785  100  7785    0     0  2270k      0 --:--:-- --:--:-- --:--:-- 7602k
* Connection #0 to host localhost left intact
```

Compare to fixed version:

```
23:07 $ curl -vk http://localhost:5000/react-swap@1.3.1/build.zip > b.zip
*   Trying 127.0.0.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /react-swap@1.3.1/build.zip HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.45.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Content-Type: application/zip; charset=utf-8
< Cache-Control: public, max-age=31536000
< Date: Thu, 17 Dec 2015 12:07:19 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
<
{ [4369 bytes data]
100  4361    0  4361    0     0   223k      0 --:--:-- --:--:-- --:--:--  250k
* Connection #0 to host localhost left intact
```

**Comment by nkbt** [comment]
@mjackson :wave:

**Comment by mjackson** [comment]
:+1: Thanks, @nkbt!

**Comment by mjackson** [comment]
BTW, I setup npmcdn.com to automatically deploy when new code is pushed to master. So whenever we merge a new version should be deployed.
