### PR TITLE
Automatically generate bower.zip package based on bower.json, fixes #6 

### LINKED ISSUE #6: Deal with bower?
I don't know if this is something we really need to think about, but if we're hoping to make npmcdn.com really eliminate the need for bower I think this could be handy...

If you do this: `bower install https://npmcdn.com/lodash` it totally works, but what gets saved to disk is this:

```
~/Desktop/tmp
🚀  $ tree .
.
├── bower.json
└── bower_components
    └── lodash
        └── index

2 directories, 2 files
```

The resulting file is simply called `index` with no extension at all. If you have a version on it: `bower install https://npmcdn.com/lodash@3.9.3` then you get:

```
~/Desktop/tmp
🚀  $ tree .
.
├── bower.json
└── bower_components
    └── lodash@3.9
        └── index.3

2 directories, 2 files
```

Which is quite odd I think, and even though technically it should still work fine, I wouldn't be surprised if issues cropped up when people commit their `bower_components` directory and deploy that and then their server doesn't know what headers to set because the file extension is wrong.

Basically what needs to happen is the url that bower is curling needs to end in the desired extension. However we can't just simply allow for `https://npmcdn.com/lodash@3.9.3.js` accross the board because then we'd need `https://npmcdn.com/lodash.js` and there are some packages that have `.js` in the name ([for example](https://www.npmjs.com/package/is.js)).

So I'm not certain of the best approach, but the more straightforward the better I think... I like the idea of allowing you to grab any file in the package as we have now, so I don't think we should change that behavior, but we need to come up with a way of allowing the last `/` URL part to be the desired name of the file.

## Skip to the next header...

So what if we had a query param to indicate that the last `/` URL part shouldn't be part of the file search but should actually part of the name? Something like this:

```
https://npmcdn.com/bootstrap@3.3.5/dist/css/bootstrap.css/whatever-i-want.css?lastIsFilename=true
https://npmcdn.com/bootstrap@3.3.5/dist/js/bootstrap.js/whatever-i-want.js?lastIsFilename=true
```

:point_up_2: contrived example... Bootstrap would actually work out alright in this case...

I'm not wild about the `lastIsFilename` query param name, but I think you get the idea. This would result in bower downloading with something like this:

## Skip to here

Turns out that some of my assumptions were wrong. Given this kind of `bower.json`:

```javascript
"dependencies": {
  "bootstrap.css": "https://npmcdn.com/bootstrap@3.3.5/dist/css/bootstrap.css",
  "bootstrap.js": "https://npmcdn.com/bootstrap@3.3.5/dist/js/bootstrap.js"
}
```

That results in this file structure

```
~/Desktop/tmp
🚀  $ tree .
.
├── bower.json
└── bower_components
    ├── bootstrap.css
    │   └── index.css
    └── bootstrap.js
        └── index.js

3 directories, 3 files
```

:-( Meaning that bower isn't using just the last filename and using that... But it *is* using the extension for the extension of `index` which pretty much solves the issue anyway. So basically all that needs to happen is the URL needs to be able to end in the extension of your choice... What do you think we could do to make that happen?

### PR DESCRIPTION
**Pull request by nkbt**
I am going to add unit tests for this one bit later.

Logic is straightforward:
1. request `bower.zip` (configurable bower package filename)
2. parse bower.json for files from `main` section
3. create `bower.zip` that contains all files from `main` section + bower.json file itself
4. serves it as any other file

Currently zip is corrupted (blocked by #16) but works fine with those changes.

Note: I used ES6 promises and ES6 syntax to simplify code, but if necessary, can easily convert it back to match rest of the code (I did it initially but code looked much bigger)

URL parsing is not changed. URL examples:

https://npmcdn.com/react@0.14.2/bower.zip
https://npmcdn.com/react-dom@0.14.2/bower.zip
https://npmcdn.com/history@1.12.5/bower.zip
https://npmcdn.com/react-router@1.0.0/bower.zip

Usage with bower:

```
bower install https://npmcdn.com/react@0.14.2/bower.zip
```

TODO: 
1. Unit tests
2. README update

### CODE REVIEW

**Comment by nkbt** [comment]
ping @mjackson @kentcdodds 

I reckon this one is sort of WIP, needs tests and README. Just wanted to share what is done so far. Optionally tests and readme can be completed in separate PR.

**Comment by nkbt** [comment]
@JedWatson you will like this one

**Comment by JedWatson** [comment]
@nkbt I do :grinning:

**Comment by nkbt** [comment]
I've published a new version of `react-swap` with `bower.json` in the package. Works perfectly.



README and front-page updated with new info accordingly.

File: modules/createBowerPackage.js [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+        // add `bower.json` file with updated version
+        zip.append(JSON.stringify(bowerConfig, null, 2), { name: 'bower.json' })
+
+        // add all files from `main` section of Bower config
+        files.forEach(file => zip.file(joinPaths(tarballDir, file), { name: file }))
+        zip.finalize()
+      })
+    })
+
+const createBowerPackage = ({ tarballDir }, callback) =>
```
Comment (mjackson) [inline modules/createBowerPackage.js]: nit: Can you please stick with existing code style? i.e. use `function` declarations instead of `const` + `=>`. Thanks!

File: package.json [hunk 2]
```diff
@@ -5,7 +5,8 @@
   "author": "Michael Jackson",
   "config": {
     "registryURL": "https://registry.npmjs.org",
-    "port": 5000
+    "port": 5000,
+    "bowerBundle": "/bower.zip"
```
Comment (mjackson) [inline package.json]: :+1: for the approach you're taking here.

File: modules/serveNPMPackageFile.js [hunk 3]
```diff
@@ -11,6 +11,9 @@ import getPackage from './getPackage'
 import resolveFile from './resolveFile'
 import getProperty from './getProperty'
 import getMaxAge from './getMaxAge'
+import createBowerPackage from './createBowerPackage'
+
+const bowerBundle = process.env.BOWER_BUNDLE || process.env.npm_package_config_bowerBundle
```
Comment (mjackson) [inline modules/serveNPMPackageFile.js]: nit: module-level constants should begin with a capital letter

File: modules/createBowerPackage.js [hunk 4]
```diff
@@ -0,0 +1,55 @@
+import { join as joinPaths} from 'path'
+import { stat as statFile, readFile, createWriteStream } from 'fs'
+import getProperty from './getProperty'
+import archiver from 'archiver'
+
+
+const promisify = func => (...args) =>
```
Comment (mjackson) [inline modules/createBowerPackage.js]: I'd really like to avoid using promises if we can.

File: README.md [hunk 5]
```diff
@@ -24,3 +24,16 @@ npm-http-server recognizes URLs in the format `/package@version/path/to/file` wh
...
+npm-http-server recognizes a special path to serveBower packages `/package@version/bower.zip` where:
+
+    package         The @scope/name of an npm package (scope is optional)
+    version         The version, version range, or tag
+
+`bower.zip` file is created dynamically based on `bower.json` found within a package.
+It contains of, actually, `bower.json` and all files, listed in its `main` section.
+
+Version number is replaced with the one from `package.json` so there is no need
+to manually update it.
```
Comment (mjackson) [inline README.md]: We shouldn't need to re-explain the `package/version` portion of the URL here. That part is the same for any npmcdn URL. Instead, the only part that needs documentation here is the `/bower.zip` path.

**Comment by mjackson** [comment]
Thanks for this PR, @nkbt! I think @kentcdodds may be interested to see this as well before we merge.

I've never actually used bower (thankfully), so I can't really comment on how useful this would be. But it seems like it would satisfy @kentcdodds' request in #6 as well.

Also, in general, please try to stick with the existing code style as much as you can @nkbt. Just take a look at the other files in the repo and do the same thing you see being done there. That would save me some time when reviewing PRs so we can get down to the meat instead of nitpicking.

**Comment by kentcdodds** [comment]
Thanks for the mention @mjackson. I've actually been watching and lightly reviewing these PRs. Exciting stuff!

If I understand correctly, when this is finished and merged I'll be able to do:

```
bower install https://npmcdn.com/angular-formly@^7.3.9/bower.zip
```

And that will install the package based on the `bower.json` correct? So I can stop publishing my generated files to GitHub and point people using dead tech to npmcdn :-) That'd be fantastic.

**Comment by mjackson** [comment]
Ya, that's the idea.

File: modules/createBowerPackage.js (hunk 4 above)
Comment (XVincentX) [inline modules/createBowerPackage.js]: Whoa...may I ask you why?

File: modules/createBowerPackage.js (hunk 1 above)
Comment (nkbt) [inline modules/createBowerPackage.js]: Absolutely. No worries, will update syntax accordingly.

> Note: I used ES6 promises and ES6 syntax to simplify code, but if necessary, can easily convert it back to match rest of the code (I did it initially but code looked much bigger)

File: modules/createBowerPackage.js (hunk 4 above)
Comment (nkbt) [inline modules/createBowerPackage.js]: That is no problem. I have couple of concurrent things going on there, so dealing with callbacks will be a pain.

What about [async](https://github.com/caolan/async)?

PS: and yeah, why? As functional programming adept I do love promises ;)

File: README.md (hunk 5 above)
Comment (nkbt) [inline README.md]: Docs writing is not my best treat for sure =). Thanks, will do

File: modules/createBowerPackage.js (hunk 4 above)
Comment (mjackson) [inline modules/createBowerPackage.js]: I've been an advocate of promises for several years now. I've spoken about them at conferences, encouraged others to use them, and been an active participant in discussions around evolving the promise API. But I'm over it now, for a few reasons:

- If you're not extremely careful, it's easy to swallow errors. After years of using them, I still occasionally accidentally wrote code that swallowed errors.
- Promises force everything to happen asynchronously, which removes the option for code to run synchronously. Most of the time I use them, I'm not actually interested in the async guarantee that promises make. Instead, I'm more interested in just having a generic way to specify some code that needs to run later. Callbacks let me run my code either async or sync, which I like.

**Comment by nkbt** [comment]
@kentcdodds Yep. That is exactly how it works. `bower install https://npmcdn.com/angular-formly@^7.3.9/bower.zip` would install it as the whole package with all deps and correct current version.

**Comment by kentcdodds** [comment]
Hug :+1: from me then! :D

File: modules/createBowerPackage.js (hunk 4 above)
Comment (sindresorhus) [inline modules/createBowerPackage.js]: > If you're not extremely careful, it's easy to swallow errors. After years of using them, I still occasionally accidentally wrote code that swallowed errors.

I agree defaulting promises to swallow errors was a horrible design decision, but it *can* be solved with tooling. Chrome DevTools reports unhandled rejections, and for Node.js you could use [`loud-rejection`](https://github.com/sindresorhus/loud-rejection).

Comment (nkbt) [inline modules/createBowerPackage.js]: Node has special handler for uncaught promise errors. Similar to unhandled
exceptions.

https://github.com/nodejs/node/pull/758

Comment (mjackson) [inline modules/createBowerPackage.js]: I've tried the tools. Lots of them. I have no doubt that support for swallowed exceptions will continue to get better over the coming years now that they've made it into ES6, which is great for people who want to use them. For me, personally, I've decided to avoid them if I can. Just feels like one place I can avoid some unnecessary complexity.

Comment (petehunt) [inline modules/createBowerPackage.js]: I've never had this problem with bluebird. Have you tried it?

Comment (nkbt) [inline modules/createBowerPackage.js]: Bluebird is fast and pretty awesome. We use it pretty much everywhere now.

Comment (mjackson) [inline modules/createBowerPackage.js]: Ya, I've used Bluebird, when, Q, RSVP, and a few other more obscure promise implementations. If I'm building something really, really big then I can't really avoid them. But for something small like npmcdn I think we can.

Comment (nkbt) [inline modules/createBowerPackage.js]: Sure, that is not a problem. My initial implementation (not committed) did not use promises and was callbacks-based. I will switch to callbacks here.

File: README.md (hunk 5 above)
Comment (XVincentX) [inline README.md]: > Callbacks let me run my code either async or sync, which I like.

@mjackson Could you please elaborate? I do not really get this.

File: modules/createBowerPackage.js (hunk 4 above)
Comment (nkbt) [inline modules/createBowerPackage.js]: Just in case, promises are guaranteed to resolve synchronously. It is up to dev to resolve them either way.

Comment (nkbt) [inline modules/createBowerPackage.js]: > The resolver is called synchronously (the following is for documentation purposes and not idiomatic code):
```js
function getPromiseResolveFn() {
    var res;
    new Promise(function (resolve) {
        res = resolve;
    });
    // res is guaranteed to be set
    return res;
}
```

From http://bluebirdjs.com/docs/api/new-promise.html

**Comment by nkbt** [comment]
Updated code according to all comments.

Double-checked it works:




Oh that's pretty awesome, installs all deps too!

**Comment by kentcdodds** [comment]
This is amazingly awesome

**Comment by mjackson** [comment]
Awesome! Thanks, @nkbt!

**Comment by kentcdodds** [comment]
I'm not certain whether merging this PR is related, but I'm now getting some 503s...

screen shot 2015-12-27 at 9 22 58 am

screen shot 2015-12-27 at 9 22 22 am

**Comment by kentcdodds** [comment]
Luckily all the examples on [angular-formly.com](http://angular-formly.com/) are still working.

**Comment by mjackson** [comment]
Looks like the new `archiver` dep was missing. I added it and everything looks like it's back up. Sorry for the trouble.

**Comment by kentcdodds** [comment]
Totally working now. This is awesome! Thank you!

File: package.json [hunk 6]
```diff
@@ -27,6 +28,7 @@
     "tar-fs": "^1.8.1"
   },
   "devDependencies": {
+    "archiver": "^0.20.0",
```
Comment (nkbt) [inline package.json]: ouch! `devDependencies`... that habit of `npm install -SD`

**Comment by nkbt** [comment]
\o/ thanks @mjackson

**Comment by mjackson** [comment]
Ah! I didn't see it there.

**Comment by JedWatson** [comment]
:grinning: so awesome - thanks @nkbt and everyone for this!
